### PR TITLE
fix: sanitize commit message quotes

### PR DESCRIPTION
**Pull request by youshitsune**
Fixing issue #1, just replacing " to '.

### CODE REVIEW

**Comment by System64fumo** [comment]
I've considered this before but then i thought "But what if i accidentalyl type ' in one of my commit messages by accident"?
Ideally the solution would be to escape " like so \"

**Comment by youshitsune** [comment]
It will compile with '

**Comment by youshitsune** [comment]
If you have one or two, it doesn't matter it just looks for outer quotes

**Review by System64fumo — CHANGES_REQUESTED** [review]
I would suggest replacing tr -s with sed 's/"/\\"/g'
This preserves the original commit and feels "cleaner"

**Comment by youshitsune** [comment]
I've change it to keep original commit message.

**Review by System64fumo — APPROVED** [review]
Awesome, LGTM :+1:

**Pull request merged**
